### PR TITLE
Added better error message for footprinter function not found

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
Closes issue #46 

Screenshot 2024-10-05 at 9 36 22 AM

Please add hacktoberfest-accepted label if possible

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
looks good, can you introduce a simple test?

**Comment by seveibar** [comment]
@ChiragAgg5k as per the org biome.json you can add the `"ignore": ["package.json"]` to fix the weird package.json formatting issue https://github.com/tscircuit/plop/blob/main/template-files/biome.json

**Comment by seveibar** [comment]
@ChiragAgg5k would love to have this feature- any way to move this forward?

**Comment by ChiragAgg5k** [comment]
Sorry i am a bit confused.. move this forward how?

**Comment by ChiragAgg5k** [comment]
Screenshot 2024-10-07 at 8 47 37 AM

**Comment by ChiragAgg5k** [comment]
Screenshot 2024-10-07 at 8 48 19 AM

**Comment by ChiragAgg5k** [comment]
@seveibar I have added the test case. Please let me know if thats how you wanted it.

Also apologies for the multiple commits, i pushed some changes by mistake 😅 Hopefully you will squash anyway

**Comment by seveibar** [comment]
Can you fix the merge conflicts?

**Comment by seveibar** [comment]
@ChiragAgg5k a different PR was merged before this one was able to be merged that converted this test suite from `ava` to `bun test`, so your test should not use `ava`.

You may want to consider starting from scratch from `main` then copying over your changes, that might be easier.

In your test, make sure to test the contents of the error message, your test is OK it just needs to test the contents of the error message

**Comment by ChiragAgg5k** [comment]
i will create a new pr

**Pull request closed without merging**
