### PR TITLE
Adding SOT25

### LINKED ISSUE #43: SOT25
https://www.diodes.com/assets/Package-Files/SOT25.pdf

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
-> Adding SOT25 circuit
-> Closes #43

cc: @seveibar

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
@seveibar the layout of SOT25 has a wide width at the left-hand pins how modify the measurements to have it?

**Review by seveibar — CHANGES_REQUESTED** [review]
footprint isn't correct, check the pad positions

image

**Comment by DhairyaMajmudar** [comment]
Yeah, that's what the problem which I faced here https://github.com/tscircuit/footprinter/pull/50#issuecomment-2390621372  for adding more pin width on left hand side which fields I've to modify ?

**Review by seveibar — APPROVED** [review]

**Review by seveibar — CHANGES_REQUESTED** [review]
@anas-sarkez can you take a look at this looks weird to me

**Comment by seveibar** [comment]
Yea @DhairyaMajmudar the snapshot shows it’s not properly centered

**Comment by anas-sarkez** [comment]
@seveibar 
 SOT-23-5 and SOT-25 are typically identical in size and footprint. Both are based on the SOT-23 package standard with a 5-pin configuration.
 and we already have `SOT-23-5` `(SOT-235)`

**Comment by seveibar** [comment]
@anas-sarkez thanks thats helpful, sounds like we can close this one out

**Pull request closed without merging**
